### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vairasza** [ITT23/assignment-08-replication-tilted#6]
Micha (vairasza)
- [x] Documentation LSTM
- [x] Refactor
- [x] describe Input params (path and smartphone ip)

Tina
- [x] Video
- [x] Bilder in Doku einfügen
- [x] Documentation Handy App
- [x] Documentation pyglet gallery
- [x] edit opacity
- [x] edit width of incoming pictures
- [x] test if path to img folder works
- [x] fix app (# todo: no folder send from phone,  # todo: fix crash on umlaut in filename,  # todo: replace camera_photo with timestamp)
- [x] update apk
- [x] test with new apk

Michael
- [x] describe why we chose x paper etc. (incl paper links), describe why we used LSTM and not angle 
- [x] describe what features we did not implement/what features we extended
- [x] using prototype (collect data, process, (invert m5stack), train model, install apk, config hand app, config, pyglet gallery, start app)
- [x] add nice sample images in img folder (~5-7 images)
